### ISSUE TITLE
Cannot connect via Admin API

### ISSUE THREAD

**Issue by steakscience** [YunoHost-Apps/ghost_ynh#23] opened 2020-11-20 01:31 UTC
**Describe the bug**
Cannot connect using the Admin API.

Other details:
- Can connect to the Ghost site
- Can connect to the Content API

**Versions**
- Hardware: Raspberry Pi at home
- YunoHost version: 4.0.8.2 (stable).
- I have access to my server: Through SSH and admin portal
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: No

**To Reproduce**
*Steps to reproduce the behavior.*
Use any service that connects to Ghost's admin API.
For me, I used iA Writer (a writing app). It could not connect to my self-hosted Ghost's admin API, but could connect to Ghost.org free trial.

**Expected behavior**
Connection should not fail.

**Comment by anmol26s** [comment] 2021-02-24 17:38
Can someone test this branch and see if the issue is fixed?

$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh/tree/admin-fix

**Comment by tituspijean** [comment] 2021-07-04 11:03
Closing, assuming it was fixed by https://github.com/YunoHost-Apps/ghost_ynh/pull/36. Do not hesitate to reopen if needed.

**Closed by tituspijean** 2021-07-04 11:03 UTC
