### ISSUE TITLE
App is broken

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/ghost_ynh#8] opened 2017-01-06 20:47 UTC
Hello

Your app failed to install.
I've an error with the certificate of en.ghost.org and a 502 error after installation.

Without a check_process file, I've no log to provide you.

So, your app will be decreased at Notworking status untill these errors be corrected.

**Comment by rikmendes** [comment] 2017-01-16 14:12
confirmed, broken on 2.5 at least. 
I managed to install it by using the default settings (namely if I change /blog to anything else the app won't install and start to remove a DB that don't exist and install fail) 

Now it's installed with a bunch of errors but throwing a nginx 502.

**Comment by julienmalik** [comment] 2017-01-16 14:17
Yes I know, it's because I don't maintain this app anymore

**Comment by rikmendes** [comment] 2017-01-16 14:19
any place I can bring the error log to help another maintainer ?

**Comment by julienmalik** [comment] 2017-01-16 14:19
Just moved to Yunohost-Apps org, where it can get more love from the community

**Comment by julienmalik** [comment] 2017-01-16 14:20
@rikmendes here is a good place

**Comment by rikmendes** [comment] 2017-01-16 14:24
OK this is my log file : http://paste.yunohost.org/ividuludik.vhdl

**Comment by frju365** [comment] 2018-08-22 22:56
The app works again apparently. Thanks to @anmol26s. I close it. (thanks @zamentur for the transfer of the app)

**Closed by frju365** 2018-08-22 22:56 UTC
